config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard, path: "_" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
    resource :post, only: %i[new create]
  end
  resources :user_registration_requests, only: %i[new create]
  resources :user_registrations, only: %i[] do
    scope module: :user_registrations do
      resource :confirmation, only: %i[new create]
    end
  end
  resources :posts, only: %i[index]
  resource :session, only: %i[new create destroy]
  resource :locale, only: %i[update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "root#index"

  if Rails.configuration.action_mailer.delivery_method == :letter_opener_web
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :content, presence: true
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < Dashboard::ApplicationController
  before_action :set_new_post, only: %i[new create]

  def new; end

  def create
    if @post.update(post_params)
      @post.broadcast_prepend_to :posts
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_new_post
    @post = current_user.posts.build
  end

  def post_params
    params.expect(post: %i[content])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    posts = Post.includes(:user).order(id: :desc).limit(10)
    posts = posts.where(id: ...params[:before]) if params[:before].present?
    @posts = posts
  end
end

app/views/posts/_load_more.erb
<%= turbo_frame_tag :load_more do %>
  <%= link_to t(".load_more"), posts_path(before: last_post_id, format: :turbo_stream), data: { turbo_frame: :posts, turbo_prefetch: false } %>
<% end %>

app/views/posts/_post.html.erb
<%= tag.div class: %w[card my-2], data: { post_id: post.id } do %>
  <%= tag.div post.content, class: %w[card-body] %>
  <%= tag.div class: %w[card-footer text-body-secondary] do %>
    <%= tag.small post.user.name %>
    <%= tag.small h(post.created_at) %>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<% content_for :sidebar_current, "home" %>

<% if logged_in? %>
  <%= turbo_frame_tag :new_post, src: new_dashboard_post_path, loading: :lazy do %>
    <%= render 'loading' %>
  <% end %>
<% end %>

<%= turbo_frame_tag :posts_content do %>
  <%= turbo_stream_from :posts %>

  <%= turbo_frame_tag :posts do %>
    <%= render @posts %>
  <% end %>

  <% if @posts.present? %>
    <%= render "load_more", last_post_id: @posts.last.id %>
  <% end %>
<% end %>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append :posts do %>
  <%= render @posts %>
<% end %>

<% if @posts.present? %>
  <%= turbo_stream.replace :load_more do %>
    <%= render "load_more", last_post_id: @posts.last.id %>
  <% end %>
<% else %>
  <%= turbo_stream.remove :load_more %>
<% end %>