config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard, path: "_" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
    resource :post, only: %i[new create]
  end
  resources :user_registration_requests, only: %i[new create]
  resources :user_registrations, only: %i[] do
    scope module: :user_registrations do
      resource :confirmation, only: %i[new create]
    end
  end
  resources :posts, only: %i[index]
  resource :session, only: %i[new create destroy]
  resource :locale, only: %i[update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "root#index"

  if Rails.configuration.action_mailer.delivery_method == :letter_opener_web
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SwitchLocale
  include Loginable

  default_form_builder ApplicationFormBuilder

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ApplicationController
  before_action :require_login
end

app/controllers/user_registrations/application_controller.rb
class UserRegistrations::ApplicationController < ApplicationController
  before_action :set_user_registration

  private

  def set_user_registration
    @user_registration = UserRegistration.active.find(params.expect(:user_registration_id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navigation_link_item(path, title:, icon:, active: false, **options, &block)
    tag.li class: %w[nav-item] do
      if active
        options[:class] = Array.wrap(options[:class]) << %w[nav-link active]
        options[:aria] = (options[:aria] ||= {})
        options[:aria][:current] = "page"
      else
        options[:class] = Array.wrap(options[:class]) << %w[nav-link]
      end

      link_to(path, **options) { with_bi_icon(title, key: icon) }
    end
  end

  def navigation_delimiter = tag.li(class: %w[nav-item disabled]) { tag.hr }

  def with_bi_icon(name = nil, key:, &block)
    if block_given?
      safe_join [ bi_icon(key), yield ], " "
    else
      safe_join [ bi_icon(key), name ], " "
    end
  end

  def bi_icon(key)
    tag.i class: [ "bi", "bi-#{key}" ]
  end
end

app/views/application/_flash.html.erb
<% if alert.present? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if notice.present? %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/application/_header.html.erb
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
  <a href="/" class="d-flex align-items-center mb-4 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
    <span class="fs-4"><%= t("application_name") %></span>
  </a>
</header>

app/views/application/_loading.html.erb
<div class="d-flex justify-content-center mb-3">
  <div class="spinner-border" role="status">
    <span class="visually-hidden"><%= t(".loading") %></span>
  </div>
</div>

app/views/application/_model_error.html.erb
<% if object.errors.any? %>
  <ul class="alert alert-danger list-unstyled" role="alert">
    <% object.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/application/_sidebar.html.erb
<% sidebar = yield(:sidebar_current) %>

<ul class="nav nav-pills flex-column">
  <%= navigation_link_item root_path, title: t(".home"), icon: "house", active: sidebar == "home" %>

  <% if logged_in? %>
    <%= navigation_link_item dashboard_profile_path, title: t(".profile"), icon: "person", active: sidebar == "profile" %>
    <%= navigation_link_item dashboard_password_path, title: t(".password"), icon: "key", active: sidebar == "password" %>
    <%= navigation_link_item session_path, title: t(".sign_out"), icon: "box-arrow-right", data: { turbo_method: :delete } %>
  <% else %>
    <%= navigation_link_item new_session_path, title: t(".login"), icon: "box-arrow-in-right", active: sidebar == "login" %>
    <%= navigation_link_item new_user_registration_request_path, title: t(".sign_up"), icon: "check", active: sidebar == "signup" %>
  <% end %>

  <%= navigation_delimiter %>
  <%= navigation_link_item locale_path(lang: 'en'), title: t(".lang_en"), icon: "translate", data: { turbo_method: :patch } %>
  <%= navigation_link_item locale_path(lang: 'ja'), title: t(".lang_ja"), icon: "translate", data: { turbo_method: :patch } %>

  <% if Rails.env.development? %>
    <%= navigation_delimiter %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
        <%= with_bi_icon "DevTools", key: "tools" %>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to letter_opener_web_path, class: %w[dropdown-item], target: "_blank" do %>
            <%= with_bi_icon "Letter Opener", key: "envelope" %>
          <% end %>
        </li>
      </ul>
    </li>
  <% end %>
</ul>